name: Request Review

on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  PY_COLORS: 1

jobs:
  review:
    runs-on: namespace-profile-ghostty-xsm
    steps:
      - uses: actions/checkout@v4

      - name: Setup Cache
        uses: namespacelabs/nscloud-cache-action@v1.2.0
        with:
          path: |
            /nix
            /zig

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: ghostty
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Request Localization Review
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REVIEW_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: nix develop -c uv run .github/scripts/request_review.py
